"""Regenerate paper/baselines.bib from DOI and arXiv authoritative records."""
import re,time
from pathlib import Path
import requests

DOIS={
"ramakrishnan2022poni":"10.1109/CVPR52688.2022.01832",
"cai2024pixnav":"10.1109/ICRA57147.2024.10610499",
"zhao2023spnet":"10.1109/LRA.2023.3320014",
"zhang2024sgm":"10.1109/CVPR52733.2024.01553",
"yokoyama2024vlfm":"10.1109/ICRA57147.2024.10610712",
"yu2023l3mvn":"10.1109/IROS55552.2023.10342512",
"zhang2024trihelper":"10.1109/IROS58592.2024.10802670",
"yuan2024gamap":"10.52202/079017-1244",
"yin2025unigoal":"10.1109/CVPR52734.2025.01775",
"nie2025wmnav":"10.1109/IROS60139.2025.11246684",
"cao2025cognav":"10.1109/ICCV51701.2025.00891",
"zhang2025fbn":"10.1109/ICCV51701.2025.01816",
"zhang2025apexnav":"10.1109/LRA.2025.3606388",
"huang2023vlmaps":"10.1109/ICRA48891.2023.10160969",
"takmaz2023openmask3d":"10.52202/075280-2989",
"jatavallabhula2023conceptfusion":"10.15607/RSS.2023.XIX.066",
"shafiullah2023clipfields":"10.15607/RSS.2023.XIX.074",
}
ARXIV={
"chaplot2020semexp":"2007.00643","majumdar2022zson":"2206.12403",
"zhou2023esc":"2301.13166","wu2024voronav":"2401.02695",
"long2024instructnav":"2406.04882","liu2025toponav":"2509.01364",
"yin2024sgnav":"2410.08189","ko2024care":"2409.04837",
"chabal2025fomnav":"2512.01009","ao2026reasonnavi":"2602.15864",
"cai2026intentnav":"2606.08029","huang2023vlmaps_arxiv":"2210.05714",
"takmaz2023openmask3d_arxiv":"2306.13631","jatavallabhula2023conceptfusion_arxiv":"2302.07241",
"shafiullah2023clipfields_arxiv":"2210.05663","nie2025wmnav_arxiv":"2503.02247",
"cao2025cognav_arxiv":"2412.10439","zhang2025apexnav_arxiv":"2504.14478",
"yin2025unigoal_arxiv":"2503.10630","zhang2024trihelper_arxiv":"2403.15223",
"yuan2024gamap_arxiv":"2410.23978","cai2024pixnav_arxiv":"2309.10309",
"yokoyama2024vlfm_arxiv":"2312.03275","yu2023l3mvn_arxiv":"2304.05501",
"zhang2025wmnav":"2503.02247",
"wang2026consistnav":"2605.09869",
}

# CVF publication records that are newer than the current Crossref index.
# These fields are copied from the publisher's official paper pages.
CVF_ENTRIES={
"wang2026trajrag": """@inproceedings{wang2026trajrag,
  author={Wang, Yiyao and Zhang, Sixian and Zhang, Keming and Song, Xinhang and Du, Songjie and Jiang, Shuqiang},
  title={TrajRAG: Retrieving Geometric-Semantic Experience for Zero-Shot Object Navigation},
  booktitle={Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR)},
  month={June}, year={2026}, pages={15166--15176}
}""",
"jiang2026hecknav": """@inproceedings{jiang2026hecknav,
  author={Jiang, Xianshun and Xiong, Yao and Gao, Xiangbo and Huang, Yanjia and Tu, Zhengzhong},
  title={HeckNav: Interpretable Heuristic Knowledge Navigation via Bayesian Probabilistic Inference},
  booktitle={Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition Workshops (CVPRW)},
  month={June}, year={2026}, pages={1040--1047}
}""",
}

def get(url,accept=None):
    headers={"User-Agent":"SSTG-Nav-benchmark/1.0 (bibliography regeneration)"}
    if accept:headers["Accept"]=accept
    last=None
    for i in range(5):
        try:
            r=requests.get(url,headers=headers,timeout=60);r.raise_for_status();return r.text
        except Exception as e:last=e;time.sleep(2**i)
    raise last

def rekey(text,key):
    text=text.replace("â€“","--").replace("–","--")
    text=re.sub(r"month=([A-Za-z]+)",r"month={\1}",text)
    return re.sub(r"(@\w+\s*\{)[^,]+,",r"\g<1>"+key+",",text,count=1)

def main():
    entries=[]
    for key,doi in DOIS.items():
        url="https://api.crossref.org/works/"+requests.utils.quote(doi,safe="")+"/transform/application/x-bibtex"
        entries.append(rekey(get(url,"application/x-bibtex").strip(),key))
    # ArXiv-only and duplicate provenance entries are retained deliberately:
    # the *_arxiv keys let authors cite a preprint when the publisher record is inaccessible.
    for key,aid in ARXIV.items(): entries.append(rekey(get(f"https://export.arxiv.org/bibtex/{aid}").strip(),key))
    entries.extend(CVF_ENTRIES.values())
    header=("% Generated by tools/build_bibliography.py from DOI/Crossref and arXiv.\n"
            "% Do not copy the placeholder entries from SSTGNavPaper/reference.bib.\n\n")
    out=Path("paper/baselines.bib");out.parent.mkdir(parents=True,exist_ok=True)
    out.write_text(header+"\n\n".join(entries)+"\n")
    print(f"wrote {out}: {len(entries)} verified entries")
if __name__=="__main__":main()
